### ISSUE TITLE
Freeze during pressing Alt key

### ISSUE THREAD

**Issue by ont** [mirmik/zencad#16]
Sometimes app freeze with this error in console:
```
GUI: window bind success
GUI: restore saved eye location
Traceback (most recent call last):
  File "/home/ont/.local/pipx/venvs/zencad/lib/python3.7/site-packages/zencad/gui/viewadaptor.py", line 270, in mouseMoveEvent
    self.onMouseMove(e.buttons(), e.pos())
  File "/home/ont/.local/pipx/venvs/zencad/lib/python3.7/site-packages/zencad/gui/viewadaptor.py", line 232, in onMouseMove
    if not self.alt_pressed:
AttributeError: 'DisplayWidget' object has no attribute 'alt_pressed'
```
I use https://github.com/i3/i3 as my window manager and bind `alt` key for switching between windows and desktops.

**Comment by mirmik** [comment]
I remove situation when it can be in uninitialized state. After the fix, the error should stop happening.

Now in zencad alt key is alternate way to model rotation (This way was added specifically for development on a laptop). How it interfere with the alt key switch window case.
